create table if not exists public.services (
  id bigint generated by default as identity primary key,
  provider_id uuid references auth.users(id) on delete cascade,
  title text not null,
  provider_name text not null,
  category text not null,
  location text not null,
  rating numeric(2, 1) not null default 0,
  starting_price integer not null default 0,
  image_url text,
  description text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.services enable row level security;

create policy "Published services are public"
  on public.services for select
  using (is_active = true);

create policy "Providers manage their own services"
  on public.services for all
  using (auth.uid() = provider_id)
  with check (auth.uid() = provider_id);
